const USAGE_ACTIVATE = "QUICK_LOGIN_REGISTER"; //识别注册验证码

const BUSINESS = "business"; //电商通枚举类型

const USER_IDENTITY = "USER_IDENTITY";

const USER_IDENTITY_BACK = "USER_IDENTITY_BACK ";

const HAND_USER_IDENTITY = "HAND_USER_IDENTITY ";

const PERSONAL = "PERSONAL";
const ENTERPRISE = "ENTERPRISE";

//联系人关系
const CONTACT_RELATIONSHIP = "CONTACT_RELATIONSHIP";

//亲属关系
const FAMILY_RELATIONSHIP = "RELATIONSHIP";

//其它联系人
const RELATIONSHIP = "RELATIONSHIP";

const MARITAL = "MARITAL";

const INDUSTRY = "INDUSTRY";

//还款来源
const PAYMENT = "PAYMENT";

//年收入
const ANNUAL_SALARY = "ANNUAL_SALARY";

//借款用途
const USAGE_LOAN = "USAGE_LOAN";
const LOAN = "LOAN";

//营业执照
const COM_BUSINESS_LICENSE = "COM_BUSINESS_LICENSE";

//居住经营地证明
const DOMICILE_BUSINESS_CERTIFICATE = "DOMICILE_BUSINESS_CERTIFICATE";

//人行报告
const BANK_CREDIT_REPORT = "BANK_CREDIT_REPORT";

//其他资料
const USER_OTHER_MATERIAL = "USER_OTHER_MATERIAL";

//企业征信
const COM_CREDIT_AUTHORIZATION = "COM_CREDIT_AUTHORIZATION";

//公司公章
const COM_COMPANY_SEAL = "COM_COMPANY_SEAL";

//法人身份证
const LEGAL_PERSON_IDENTIT = "LEGAL_PERSON_IDENTIT";

//营业执照正本(开户)
const COM_BUSINESS_LICENSE_OPEN_ACCOUNT = "COM_BUSINESS_LICENSE_OPEN_ACCOUNT";

//开户许可证正本
const COM_ACCOUNT_PERMITS = "COM_ACCOUNT_PERMITS";

//机构信用代码证
const AGENCY_CREDIT_CODE = "AGENCY_CREDIT_CODE";

//对公账户电子回单
const COM_RETURN_RECEIPT = "COM_RETURN_RECEIPT";

//交易类型
const FEE_TYPE = "FEE_TYPE";

//授信申请状态
const CREDIT_STATUS = "CREDIT_STATUS";
const CREDIT_GROUP = "CREDIT";

//担保状态
const GUARANTEE_STATUS = "GUARANTEE_STATUS";
const GUARANTEE_GROUP = "GUARANTEE";

//担保状态
const AUTH_UNREGISTERED = "UNREGISTERED";
const AUTH_BE_CERTIFIED = "BE_CERTIFIED";
const AUTH_TO_INFORMATION = "TO_INFORMATION";
const AUTH_AUDIT = "AUDIT";
const AUTH_FAIL = "FAIL";
const AUTH_BE_SIGN = "BE_SIGN";
const AUTH_REFUSE = "REFUSE";
const AUTH_CANCEL = "CANCEL";
const AUTH_INVALID = "INVALID";
const AUTH_UPDATE = "UPDATE";
const AUTH_SIGNED = "SIGNED";

//还款方式
const REPAY_WAY = "REPAY_WAY";

//还款状态
const REPAY_STATUS = "REPAY_STATUS";

//还款状态-已还款
const REPAY_REPAYED = "REPAYED";

//充值
const RECHARGE = "RECHARGE";

//提现
const WITHDRAW = "WITHDRAW";

//支付方式
const REPAY_WAY_P_D = "P_D";
const REPAY_WAY_P_W = "P_W";

//借款状态
const LOAN_STATUS = "LOAN_STATUS";
const LOAN_GROUP = "LOAN";

//审核中	1
const LOAN_AUDIT = "AUDIT";

//审核不通过	借款申请状态	2
const LOAN_FAIL = "FAIL";

//待签约	借款申请状态	4
const LOAN_BE_SIGN = "BE_SIGN";

//已签约	借款申请状态	8
const LOAN_SIGNED = "SIGNED";

//已拒绝签约	借款申请状态	16
const LOAN_REFUSING_SIGN = "REFUSING_SIGN";

//放款中	32
const LOAN_IN_LOAN = "IN_LOAN";

//还款中	借款申请状态	64
const LOAN_REPAYMENTS = "REPAYMENTS";

//已提前还款	借款申请状态	128
const LOAN_EARLY_REPAYMENT = "EARLY_REPAYMENT";

//已逾期	256
const LOAN_OVERDUE = "OVERDUE";

//已失效 512
const LOAN_INVALID = "INVALID";

//终止放款	1024
const LOAN_TERMINATE_LOAN = "TERMINATE_LOAN";

//已还款
const LOAN_REIMBURSEMENT = "REIMBURSEMENT";

//还款方式
const REPAYMENT_TYPE = "REPAYMENT_TYPE";

//数据字典参数
const LOAN_AMOUNT_MIN = "LOAN_AMOUNT_MIN";

/*放款类型*/
//财务放款
const FINANCIAL_LENDING = "FINANCIAL_LENDING";
//第三方放款
const THIRD_PARTY_LENDING = "THIRD_PARTY_LENDING";

const PERSONAL_RESIDENCE_BOOK = "PERSONAL_RESIDENCE_BOOK"; //家庭情况证明
const COM_LOANS_PRINTSCREEN = "COM_LOANS_PRINTSCREEN"; //淘宝贷款截图
const COM_SHOP_DATA_PRINTSCREEN = "COM_SHOP_DATA_PRINTSCREEN"; //店铺数据截图
const SPOUSE_BANK_CREDIT_REPORT = "SPOUSE_BANK_CREDIT_REPORT"; //配偶人行报告
const COM_PLACE_PRINTSCREEN = "COM_PLACE_PHOTO"; //场地照片
const COM_STAFF_CONTACTS_LIST = "COM_STAFF_CONTACTS_LIST"; //员工通讯录
const COM_INVOICE_PHOTO = "COM_INVOICE_PHOTO"; //增值税开票数据
const SHOP_PHOTO = "SHOP_PHOTO"; //烟草通店铺
const TOBACCO_RETAIL_LICENSE = "TOBACCO_RETAIL_LICENSE"; //烟草零售许可
export default {
  PERSONAL_RESIDENCE_BOOK,
  COM_LOANS_PRINTSCREEN,
  COM_SHOP_DATA_PRINTSCREEN,
  SPOUSE_BANK_CREDIT_REPORT,
  COM_PLACE_PRINTSCREEN,
  COM_STAFF_CONTACTS_LIST,
  COM_INVOICE_PHOTO,
  USAGE_ACTIVATE,
  BUSINESS,
  USER_IDENTITY,
  USER_IDENTITY_BACK,
  HAND_USER_IDENTITY,
  PERSONAL,
  ENTERPRISE,
  CONTACT_RELATIONSHIP,
  FAMILY_RELATIONSHIP,
  RELATIONSHIP,
  MARITAL,
  INDUSTRY,
  PAYMENT,
  ANNUAL_SALARY,
  USAGE_LOAN,
  LOAN,
  COM_BUSINESS_LICENSE,
  DOMICILE_BUSINESS_CERTIFICATE,
  BANK_CREDIT_REPORT,
  USER_OTHER_MATERIAL,
  COM_CREDIT_AUTHORIZATION,
  COM_COMPANY_SEAL,
  LEGAL_PERSON_IDENTIT,
  COM_BUSINESS_LICENSE_OPEN_ACCOUNT,
  COM_ACCOUNT_PERMITS,
  AGENCY_CREDIT_CODE,
  COM_RETURN_RECEIPT,
  FEE_TYPE,
  CREDIT_STATUS,
  CREDIT_GROUP,
  GUARANTEE_STATUS,
  GUARANTEE_GROUP,
  AUTH_UNREGISTERED,
  AUTH_BE_CERTIFIED,
  AUTH_TO_INFORMATION,
  AUTH_AUDIT,
  AUTH_FAIL,
  AUTH_BE_SIGN,
  AUTH_REFUSE,
  AUTH_CANCEL,
  AUTH_INVALID,
  AUTH_UPDATE,
  AUTH_SIGNED,
  REPAY_WAY,
  REPAY_STATUS,
  RECHARGE,
  WITHDRAW,
  REPAY_WAY_P_D,
  REPAY_WAY_P_W,
  LOAN_STATUS,
  LOAN_GROUP,
  LOAN_AUDIT,
  LOAN_FAIL,
  LOAN_BE_SIGN,
  LOAN_SIGNED,
  LOAN_REFUSING_SIGN,
  LOAN_IN_LOAN,
  LOAN_REPAYMENTS,
  LOAN_EARLY_REPAYMENT,
  LOAN_OVERDUE,
  LOAN_INVALID,
  LOAN_TERMINATE_LOAN,
  LOAN_REIMBURSEMENT,
  LOAN_AMOUNT_MIN,
  FINANCIAL_LENDING,
  THIRD_PARTY_LENDING,
  SHOP_PHOTO,
  TOBACCO_RETAIL_LICENSE
};
